const canvas=document.querySelector('#field'),ctx=canvas.getContext('2d'),core=document.querySelector('#core'),rail=document.querySelector('#rail');
let W=0,H=0,dpr=1,pts=[],scrollTarget=0,scrollNow=0,mx=0,my=0,pmx=0,pmy=0,day=false;
const clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n)); const lerp=(a,b,t)=>a+(b-a)*t;
function resize(){dpr=Math.min(devicePixelRatio||1,1.5);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);pts=Array.from({length:W<800?45:110},()=>({x:Math.random()*W,y:Math.random()*H,z:Math.random(),s:Math.random()*1.2+.3,v:Math.random()*.07+.015}))}
function scroll(){const max=document.documentElement.scrollHeight-innerHeight;scrollTarget=max?scrollY/max:0}
addEventListener('resize',resize);addEventListener('scroll',scroll,{passive:true});addEventListener('pointermove',e=>{mx=(e.clientX/W-.5)*2;my=(e.clientY/H-.5)*2},{passive:true});
document.querySelector('#mood').addEventListener('click',()=>{day=!day;document.body.classList.toggle('day',day);document.querySelector('#mood em').textContent=day?'DAY':'NIGHT'});
function render(){scrollNow=lerp(scrollNow,scrollTarget,.06);pmx=lerp(pmx,mx,.05);pmy=lerp(pmy,my,.05);ctx.clearRect(0,0,W,H);for(const p of pts){p.y-=p.v*(1+p.z);if(p.y<-5)p.y=H+5;ctx.beginPath();ctx.arc(p.x+pmx*p.z*6,p.y+pmy*p.z*4,p.s*(.6+p.z),0,Math.PI*2);ctx.fillStyle=day?`rgba(50,70,82,${.05+p.z*.11})`:`rgba(142,194,225,${.07+p.z*.24})`;ctx.fill()}
const p=scrollNow;let x=0,y=0,s=1,rx=-4,ry=-11,op=1;if(p<.18){const t=clamp((p-.02)/.16);s=lerp(1,1.45,t);x=lerp(0,-160,t);y=lerp(0,20,t);ry=lerp(-11,1,t)}else if(p<.37){const t=clamp((p-.18)/.19);s=lerp(1.45,.72,t);x=lerp(-160,260,t);y=lerp(20,-60,t);rx=lerp(-4,12,t);ry=lerp(1,-22,t)}else if(p<.64){const t=clamp((p-.37)/.27);s=lerp(.72,.46,t);x=lerp(260,-320,t);y=lerp(-60,80,t);op=lerp(.8,.38,t)}else{const t=clamp((p-.64)/.22);s=lerp(.46,.24,t);x=lerp(-320,80,t);y=lerp(80,-150,t);op=lerp(.38,.08,t)}core.style.opacity=op;core.style.transform=`translate(-50%,-50%) translate3d(${x+pmx*9}px,${y+pmy*6}px,0) scale(${s}) rotateX(${rx-pmy*1.5}deg) rotateY(${ry+pmx*2.2}deg)`;if(rail)rail.style.transform=`translateX(${lerp(-40,10,clamp((p-.12)/.15))}px)`;requestAnimationFrame(render)}resize();scroll();render();
